# .github/workflows/python-test.yml
name: 🐍 Testar Exercícios Python

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checar o código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependências (se houver)
        run: |
          python -m pip install --upgrade pip
          # pip install -r requirements.txt

      - name: Rodar todos os exercícios
        run: python test_all.py
