[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"
[tool.black]
exclude = '''
/(
    Mundo01/Desafios/34/34.py
    Mundo01/Exercicios/ex033.py
    Mundo01/Exercicios/ex034.py
)/
'''
