[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"
[tool.black]
exclude = '''
/(
    /home/runner/work/Python/Python/Mundo01/Desafios/34/34.py
    /home/runner/work/Python/Python/Mundo01/Exercicios/ex033.py
    /home/runner/work/Python/Python/Mundo01/Exercicios/ex034.py
)/
'''
[project]
name = "meu_pacote_python"
version = "1.0.8"  # OBRIGATÓRIO
description = "Meus exercícios de python com DevOps"
authors = [{name = "Igor Pompeo", email = "pompbass@gmail.com"}]
license = {text = "MIT"}  # Nova sintaxe SPDX
readme = "README.md"
requires-python = ">=3.8"
dynamic = ["version"]
dependencies = [
    "requests>=2.25.0",
]
