name: pre-commit

on:
  push:
    branches: [master, main, feature/*, bugfix/*]
  pull_request:
    branches: [master, main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Rodar pre-commit nos arquivos
        run: pre-commit run --all-files
